name: CI for API and client

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Run tests
        run: |
          cd client
          npm run test:unit
      - name: Run build
        run: |
          cd client
          npm run build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "A changes are passed on tests and build"
          branch: "main"
          title: "New aproved changes"
          body: "A changes are passed on tests and build"
          labels: "update-client"
          reviewers: "${{ github.actor }}"
          assignees: "${{ github.actor }}"
      # Analyze repositories source metrics:
      # Create (or update) CODE_METRICS.md file.
      - name: Analyze repositories source metrics
        uses: githubocto/repo-visualizer@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CODE_METRICS.md
          title: "Code Metrics"
          # Optional: Set the branch to push the generated markdown file to.
          branch: "main"
          commit-message: "Update CODE_METRICS.md"
          author-name: "github-actions[bot]"
          author-email: "41898282+github-actions[bot]@users.noreply.github.com"
          path: "."
          extensions: "js,jsx,ts,tsx,css,scss,html,md"
          exclude: "node_modules"
         
       


