name: Pipeline for API and client

on: 
  push:
    branches: 
      - development
      - '!master'
  workflow_dispatch:

jobs:
  build_test:
    name: build e test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use nodeJs-16.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.0
    - name : Install dependencies and build
      run: |
          cd client
          npm install
          npm run build
          cd ../api
          sudo apt-get update
          sudo apt-get install python3-pip python3-venv python3-dev libpq-dev postgresql postgresql-contrib -y
          # sudo systemctl start postgresql.service
          # pg_isready
          # sudo psql -U postgres -c "CREATE USER myuser WITH PASSWORD 'password'"
          sudo pip3 install virtualenv
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip3 install django djangorestframework psycopg2 django-cors-headers
          git add * 
          git stash
          git pull
    - name: Test client and api
      run: |
          cd client
          npm run test:unit
          # cd ../api
          # python manage.py test
    - name: Send custom variable to Meercode Build
      uses: meercodeio/meercode-custom-variable@0.1.0
      with:
        meercode-token: 'IPzPQBHDjG3rdrk9HsQEwPpW9x428yo5'
        url: 'https://game-moura.atlassian.net/browse/MTPG-8?atlOrigin=eyJpIjoiNmRjN2NhYjU2ODljNDYwMzhhMTFlY2M2OTc0YzllNmMiLCJwIjoiaiJ9'
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: 'Merge pull request #${{ github.event.number }} from ${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}'
        title: 'Merge pull request #${{ github.event.number }} from ${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}'
        body: 'Merge pull request #${{ github.event.number }} from ${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}'
        branch: 'merge/${{ github.event.pull_request.head.ref }}'
        base: 'main'
        delete-branch: false
        labels: 'merge'
        
      