name: Pipeline for API and client

on: 
  push:
    branches: 
      - development
      - '!master'
  workflow_dispatch:

jobs:
  build_test:
    name: build e test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use nodeJs-16.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.0
    - name : Install dependencies and build
      run: |
          cd client
          npm install
          npm run build
          cd ../api
          sudo apt-get update
          sudo apt-get install python3-pip python3-venv python3-dev libpq-dev postgresql postgresql-contrib -y
          sudo systemctl start postgresql.service
          pg_isready
          sudo pip3 install virtualenv
          sudo python3 -m venv venv
          source venv/bin/activate
          sudo pip3 install django djangorestframework psycopg2 django-cors-headers
    - name: Test client and api
      run: |
          cd client
          npm run test:unit
          cd ../api
          python manage.py test

  
        
      