name: Pipeline for API and client

on: 
  push:
    branches: 
      - development
      - '!master'
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          POSTGRES_HOST: 0.0.0.0
          POSTGRES_PORT: 5432
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: myuser
          POSTGRES_DB: myproject
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
  build_test:
    name: build e test
    runs-on: ubuntu-latest
    steps:
      - name: Build a client and api
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - run: |
            cd client
            npm install
            pm run build
            cd ../api
            sudo apt-get update
            sudo apt-get install python3-pip python3-venv python3-dev libpq-dev postgresql postgresql-contrib -y
            sudo pip3 install virtualenv
            sudo python3 -m venv venv
            source venv/bin/activate
            sudo pip3 install django djangorestframework psycopg2 django-cors-headers
      - name: Test client and api
        - run: |
            cd client
            npm run test:unit
            cd ../api
            python manage.py test

  
        
      